services:
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   ports:
  #     - "6389:6379"
  #   networks:
  #     - billing-network
  #   restart: unless-stopped

  django-web:
    build: .
    container_name: django-web
    env_file: .env
    volumes:
      - ./static:/app/staticfiles
    networks:
      - billing-network
    # depends_on:
    #   - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - MIKROTIK_URL=${MIKROTIK_URL}
      - MIKROTIK_USER=${MIKROTIK_USER}
      - MIKROTIK_PASS=${MIKROTIK_PASS}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS:-http://localhost,http://127.0.0.1}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost,http://127.0.0.1}
      - CELERY_BROKER_URL=redis://default:9pj2bRIgYq91Z1vVsq2PlPTUolVMpVMn96rs5Puvf9vKQyWZS5vZenkwd4TFbiY2@145.223.22.92:6378/0
      - CELERY_RESULT_BACKEND=redis://default:9pj2bRIgYq91Z1vVsq2PlPTUolVMpVMn96rs5Puvf9vKQyWZS5vZenkwd4TFbiY2@145.223.22.92:6378/0

  celery-worker:
    build: .
    container_name: celery-worker
    env_file: .env
    command: celery -A app worker -l info
    volumes:
      - ./static:/app/staticfiles
    networks:
      - billing-network
    depends_on:
      # - redis
      - django-web
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - CELERY_BROKER_URL=redis://default:9pj2bRIgYq91Z1vVsq2PlPTUolVMpVMn96rs5Puvf9vKQyWZS5vZenkwd4TFbiY2@145.223.22.92:6378/0
      - CELERY_RESULT_BACKEND=redis://default:9pj2bRIgYq91Z1vVsq2PlPTUolVMpVMn96rs5Puvf9vKQyWZS5vZenkwd4TFbiY2@145.223.22.92:6378/0

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./static:/static:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django-web
    networks:
      - billing-network

networks:
  billing-network:
    driver: bridge
