# Generated by Django 5.2.6 on 2025-10-21 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAYS_30', 'Days_30'), ('DAYS_60', 'Days_60'), ('DAYS_90', 'Days_90'), ('DAYS_120', 'Days_120'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('otp_type', models.CharField(choices=[('PASSWORD_RESET', 'Password_Reset'), ('USER_VERIFICATION', 'User_Verification'), ('TRANSACTION_VERIFICATION', 'Transaction_Verification'), ('OTHER', 'Other')], default='PASSWORD_RESET', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
