# Generated by Django 5.2 on 2026-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organization_logo_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='router_ip',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='router_password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='router_secret',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='router_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
