# Generated by Django 5.2.6 on 2025-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subsrciption_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
