# Generated by Django 5.2.6 on 2025-11-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_year',
            field=models.IntegerField(db_index=True, default=2025, help_text='Year for which the payment is made.'),
        ),
    ]
