# Generated by Django 5.2.6 on 2025-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_payment_billing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_password',
            field=models.CharField(blank=True, help_text='Hashed password for customer login authentication.', max_length=128),
        ),
    ]
